### ISSUE TITLE
Transparency no longer changes when switching to a workspace with a maximized app

### ISSUE THREAD

**Issue by jwarkentin** [rockon999/dynamic-panel-transparency#55]
I just updated the extension and now when I change from a workspace without a maximized app to a workspace with a maximized app the panel remains transparent. But if I then switch to another workspace with a maximized app it finally changes to be opaque and then remains when I switch back.

**Comment by rockon999** [comment]
Hello,

I'm sorry to here about this issue. I can't reproduce this on my setup, so I have a few questions.

Which application? (All or a specific application)
How are you switching workspaces?
Gnome version?
Any extensions that deal with the panel/workspaces?

**Comment by rockon999** [comment]
Also, Wayland or X?

**Comment by jwarkentin** [comment]
* I'm just using X on Ubuntu and I double checked to confirm it's not Wayland.
* It's happening with all applications. I've tried Chrome, Firefox and Gnome-Terminal.
* I've tried switching using the keyboard as well as using the mouse on the panel with the Top Panel Workspace Scroll extension I have installed which is how I generally switch.
* `gnome-shell --version` reports `3.20.4`
* I have several extensions that add buttons and menus to the panel but the only other extension I have that seems to do anything directly with the panel is the Top Panel Workspace Scroll one. I tried disabling it along with several others to test and see if that was affecting anything but the issue still remained.

It is also possibly worth noting that when I hit the meta/super key to go into the overview mode and back that also triggers the opacity to return to normal.

One other thing that may or may not be related is that I just switched from using the open source Nouveau graphics driver to using the proprietary Nvidia one. Unfortunately since I just switched to that as well as just updated this extension today, it's difficult to isolate the two.

I'm not sure how this is implemented but is it possible there could be a race condition or out-of-order event response where it tries to identify the workspace and whether there are any maximized applications before it's actually switched workspaces in some cases?

In case it helps I will also attach a screenshot of the extension settings from dconf. I've changed a few settings.
![screenshot from 2017-03-08 18-58-21](https://cloud.githubusercontent.com/assets/1084024/23732623/5b2a6db2-0431-11e7-87d5-791cf23970d6.png)

**Comment by jwarkentin** [comment]
Another thing I forgot to mention is that I am using a second monitor with my laptop but I tried unplugging my second monitor and just using the laptop screen and it still had the same issue. So either the second monitor is not a factor or it caches some sort of information about how many monitors are installed and doesn't update that info. My guess though would be that it's unrelated. Just wanted to help rule that out as a factor as well.

**Comment by rockon999** [comment]
I'll load up a 3.20 VM and try to replicate. There shouldn't be any race conditions as the extension specifically omits the current workspace's windows from its logic when you switch. I'll double check the code though and ensure no such issues are occuring. The logic had to be tweaked for Wayland and its possibly messing with X support.

**Comment by jwarkentin** [comment]
Ok. I've also started looking at the code and I'm trying to figure out how to dig in and debug. I've never written an extension before but I'm good with JS so once I figure out how to log some debug stuff out I might be able to help figure it out.

It's clearly receiving the right events but it seems to respond too early. Hence when I switch from a workspace with no maximized windows to one with a maximized window the panel remains transparent. But when I switch again from a workspace with a maximized window to another with a maximized window or really do anything else that triggers the check, it figures it out and make the panel opaque. It's got to somehow be checking the wrong set of windows during the transition or just checking too early.

**Comment by jwarkentin** [comment]
After playing around I've noticed another thing that might help in debugging. If I open up a window like Gnome Terminal or something and then right click on the title bar and select "Always on Visible Workspace" then as long as that is checked the panel transparency works as expected while switching workspaces. For some reason having one window that moves with me as I move workspaces magically fixes it.

**Comment by jwarkentin** [comment]
Ah, so it turns out this bug has everything to do with focus. When I switch to an empty workspace that has no open windows there nothing is focused. Switching from that empty workspace to a workspace with maximized windows then doesn't update the transparency.

If I open an unmaximized window on that previously empty workspace and switch to a workspace with a maximized window while the unmaximized window is focused then everything works fine. However, if I go back down to the workspace with the unmaximized window and click on the desktop background so the window is no longer focused and then move up to a workspace with a maximized window, the transparency won't change.

**Comment by rockon999** [comment]
Hi!

I have a few theories on why this may be happening. If you could try two things for me...

1. Go into event.js in the extension code (~/.local/share/gnome-shell/extensions/) and try commenting out any line with 'this._workspaceSwitchSig'.
2. If that doesn't work, uncomment those lines and try commenting any line with 'this._windowRestackedSig'.

Also, could you send me the 'App Tweaks' page of your extension preferences. Thanks!

**Comment by rockon999** [comment]
Also, in addition to commenting those lines try changing 'connect' to 'connect_after' on both those lines.

**Comment by jwarkentin** [comment]
Ok, so none of that helped but after some more testing I did narrow it down to a specific condition in the code that's causing the problem.

In event.js from lines 348-351 it has this:
```js
if (focused_window && focused_window.get_window_type() === Meta.WindowType.DESKTOP) {
    add_transparency = true;
    this.maximized_window =  focused_window;
}
```

That bit seems to change the value of `add_transparency` from `false` to `true` when moving from a workspace with no windows focused to a workspace with a maximized window. When I comment that out the problem is fixed. Not really sure what that's supposed to be doing though or how important it is.

**Comment by rockon999** [comment]
Do you have desktop icons enabled?

**Comment by rockon999** [comment]
The latest in the GitHub should fix the issues you are experiencing.

**Comment by jwarkentin** [comment]
Ah, yes. It must have been the desktop icons. I dropped in the latest from Github and I can confirm it solves the problem. Thanks!

**Comment by rockon999** [comment]
I had to change some handling for this fix. Would you be willing to test the latest again when you get the chance? Thanks!

**Comment by jwarkentin** [comment]
No problem! Just tested and it still appears to work correctly with your latest changes.

**Comment by rockon999** [comment]
The changes that fixed this issue have been included in v19, the latest stable release. This release is currently pending review on Gnome Extensions. As such, this issue is now closed.
